### ISSUE TITLE
Can't add coinmarketcap IDs that share ticker names in "Ticker or CUSIP" field

### ISSUE THREAD

**Issue by NewmanDaniel** [sclem/pfcrypto#12]
I'm unable to add coinmarketcap IDs that share ticker names w/ an existing security in the "Ticker or CUSIP" field.
I.E. when trying to add neo, it automatically populates the price field with the price from NeoGenomics, Inc.
The price doesn't seem to update when this occurs.
![image](https://user-images.githubusercontent.com/11379130/39683962-b2c6de7c-5186-11e8-832d-ac049f595f00.png)

**Comment by sclem** [comment]
Add a dollar sign in front of the ticker so that Personal Capital doesn't auto-complete it for you. 

Example: `$NEO` instead of `NEO`

See the README for the instructions and troubleshooting :)
