### ISSUE TITLE
Coin prices stopped updating on Feb 7, 2019

### ISSUE THREAD

**Issue by m3ltaw4y** [sclem/pfcrypto#13]
BTC, LTC, ADA, and ETH stopped updating their prices on or around Feb 7, 2019.  I've refreshed all my other accounts and logged into personal capital every day since then, but crypto holding seem to be stuck since then.

**Comment by 8pozzum** [comment]
Same problem.  I uninstalled pfcrypto on all browsers, restarted, and reinstalled.

Seems to be working now.

**Comment by jiexi** [comment]
Whitelist api.coinmarketcap.com in your adblocker. uBlock was blocking it for me, so I guess their hosts file updated recently.

**Comment by 8pozzum** [comment]
I think the api link changed.  I had to update a few spreadsheets that use it.  It all stopped working about the same time.

**Comment by 8pozzum** [comment]
Oh, and confirmed that reinstalling works.  Worked fine for the past 2 days.

**Comment by sclem** [comment]
coinmarketcap has changed their API according to their documentation: https://coinmarketcap.com/api/documentation/v1/

The api call we are using isn't even documented anymore, and doesn't work directly in the browser. It will probably break soon (v1/ticker/) For a free account you need an api key as well, which we'd have to track for each user.

Also, it used to behave where if you set limit=0 it would return all coins, but not anymore, only 100 max at a time. This means that lower ranked coins won't get tracked.

This was first made with that coinmarketcap API ~ 18 months ago, so it had a good run.. 

If someone has the skills to swap us over to a different api or transition to the new coinmarketcap api and build a ui to save the user's api token and update the documentation, that'd be great. I might not get around to this for some time and could use the help.

Until coinmarketcap turns off the old endpoint, the top 100 coins still update. 

It also looks like the calls to personalcapital's api "lag" as in the update takes but the response contains the old data. That's an entirely separate issue. Refreshing the webpage a couple times seems to make it work eventually.

**Comment by 8pozzum** [comment]
Thanks sclem, this has been a great tool.

I updated all my spreadsheets to V1 a while ago.  If it goes, I will be lost.

I appreciate all your hard work.
