### ISSUE TITLE
api.coinmarketcap.com Deprecated

### ISSUE THREAD

**Issue by rockzom** [sclem/pfcrypto#14]
"WARNING: This API is now deprecated and will be taken offline soon. Please switch to the new CoinMarketCap API to avoid interruptions in service. (https://pro.coinmarketcap.com/migrate/)"

**Comment by sclem** [comment]
the coinmarketcap api now requires an api key for all requests, even the free tier. We would have to do one of the following:

1. add a simple gui to the extension for users to store their api key (maybe in localStorage, wouldn't persist across devices).
2. hack the api key into personal capital's storage by putting it in a description field/etc for a coin (similar to how we handle public keys to update balances).
3. switch to a different provider that still allows "anonymous" accesss to coin tickers.
4.  I pay for coinmarketcap pro api, require user logins to the extension, and proxy the requests via an independent webserver.

Leaning towards option 2. Add an additional setup step to the readme to add an extra "stock"/security named "$PFCRYPTO_COINMARKETCAP_API_KEY", description field set the api key. Then refactor the extension to look for this first and use the api key in the security description to query the pro api.

**Comment by 8pozzum** [comment]
How difficult would it be to switch to:

https://api.alternative.me/v2/ticker/bitcoin/

**Comment by 8pozzum** [comment]
looks like this pulls the same data:

https://api.alternative.me/v2/ticker/?limit=0

**Comment by sclem** [comment]
Awesome, yea that should be an easy swap. We'd want to use the v1 ticker unless we want to make changes to handle the v2 json structure.

**Comment by tmlee** [comment]
How about giving the CoinGecko API a try? https://www.coingecko.com/en/api
It is public, free and open. Should be an easy implementation. I am here to help answer any questions as well!

**Comment by jiexi** [comment]
Getting 410 now. looks like coinmarketcap API is now dead

**Comment by sclem** [comment]
Just pushed the change to use api.alternative.me. It was the easiest switch now that coinmarketcap is finally dead. Extension is under review. Version will be 1.0.4 when released. If anyone wants to make a PR using a better API, I am happy to accept. api.alternative.me was the easiest switch to keep this working for now.

**Comment by didyouexpectthat** [comment]
I haven't been able to get pfcrypto working in a long time. I've logged out of personalcapital, logged back in, added new 'stock' using both methods (id, ticker)... received the new update today, still not getting any updates to coins. 

![image](https://user-images.githubusercontent.com/1329077/76686116-51eb4000-65d6-11ea-9fec-002a4e9542fc.png)
![image](https://user-images.githubusercontent.com/1329077/76686122-616a8900-65d6-11ea-868f-4939989fd643.png)

**Comment by 8pozzum** [comment]
Just sent you a beer's worth of bitcoin.

Hope others will follow suit.

**Comment by sclem** [comment]
Thanks! I refactored the code (long overdue), would appreciate any input: https://github.com/sclem/pfcrypto/pull/16

Should make it a lot easier for us to switch between ticker apis in the future, or give the user a choice as to which api they want to use.

**Comment by 8pozzum** [comment]
> Thanks! I refactored the code (long overdue), would appreciate any input: #16
> 
> Should make it a lot easier for us to switch between ticker apis in the future, or give the user a choice as to which api they want to use.

alt.me is working well most of the time.  Goes down from time-to-time on their end.  Nothing you can do about it.  I'm just documenting for posterity.

**Comment by sclem** [comment]
Closing this, alt.me works good enough.
