### ISSUE TITLE
Publish latest version for Firefox

### ISSUE THREAD

**Issue by stevenmirabito** [sclem/pfcrypto#18]
I just came across this extension, and it works great! However, it looks like the  Firefox add-on hasn't been updated since `1.0.2`, which uses the now-defunct CoinMarketCap API. Would it be possible to publish the latest version of the extension? I have the latest version loaded manually and it works fine.

Thanks!

**Comment by sclem** [comment]
Updated FF to the latest, should be live within a few hours.

**Comment by stevenmirabito** [comment]
Thank you! 🙌
