### ISSUE TITLE
Is this extension broken?

### ISSUE THREAD

**Issue by twofirstnamez** [sclem/pfcrypto#19]
Hey, I know nothing about coding/programming, but I haven't gotten this extension to work.  Is it my fault, or is it just not working right now? I saw some other comments about possible issues.

Thanks!

**Comment by didyouexpectthat** [comment]
Yes, see #20  which resolves it.

**Comment by sclem** [comment]
Chrome/FF have been updated with the fix, should be live on the stores soon.
