### ISSUE TITLE
Number of shares set to 0

### ISSUE THREAD

**Issue by jselanikio** [sclem/pfcrypto#6]
I have set up BITCOIN and ETHEREUM as holdings in a Personal Capital "Manual Investment Holdings."  I have entered my wallet address as directed — but usually moments after I save the information the number of shares is set to zero.

This happens whether I first manually enter the shares number, or if I leave it blank, or if I set it to zero.

![mypccrypto](https://user-images.githubusercontent.com/224687/34112232-ef90f376-e3d9-11e7-97ed-dafa6a1b4406.png)

**Comment by sclem** [comment]
Did you try refreshing the page after pressing "save"? The balances update on initial load.

Also that ethereum address doesn't look long enough to me.

**Comment by jselanikio** [comment]
Sorry, the ethereum address is longer but was blocked out. It's definitely the full address in the PC field. 

I just tried refreshing the screen after pressing save and the same thing happened: after about 30 seconds, the number of shares for both ETH and BTC went to zero.

I've tried manually entering the number of shares, or leaving it at zero. Either way, after a minute or so they are set to zero.

P.S. I don't think this was happening until I entered the wallet addresses, based on your recent update.

**Comment by sclem** [comment]
If you press f12 and look at the developer console when refreshing, it should print out "resolved address"... with the balance. See if those values are what is expected in your addresses. You can also use a block explorer website to verify the address is correct and has the correct number of coins.

**Comment by jselanikio** [comment]
Thanks. Very useful. So it seems that "Resolved ETHEREUM account balance for address 0xAd1C6DD3595198edf8FBdd42577Ad34eF58A6BFA as: 0" even though the balance for that wallet is definitely not zero on Coinbase.

**Comment by jselanikio** [comment]
Same for BTC.

**Comment by jselanikio** [comment]
This does not seem to be an issue with your extension, but with the addresses I'm getting from bitcoin.  I'll close this issue now. Thanks for the quick help.

**Comment by jselanikio** [comment]
Sorry, just FYI: your system (for updating shares) won't work for Coinbase accounts because of this:

https://bitcoin.stackexchange.com/questions/17113/bitcoin-address-does-not-show-transaction-balance-from-coinbase-purchase

**Comment by sclem** [comment]
So coinbase doesn't actually store your coins in your address. They hold them separately and your balance on coinbase is really an "IOU" (like a bank). If you look at the bitcoin transaction from sending coins to coinbase you can see that your final balance is 0 because coinbase has moved them to their own private storage. 

To make this extension work you'll have to use a wallet in which you control the private keys. There may be another way with coinbase, I'm not aware of one.

**Comment by jselanikio** [comment]
Yes, understood. Again, clearly not an issue with your extension. I'll look at other wallet systems. In the meantime, thanks again for quick response.
